# frozen_string_literal: true

source 'https://rubygems.org'

gem 'erb_lint'
gem 'puma'
gem 'rerun'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'sinatra'
gem 'capybara'
gem 'wdm'

group :deployment do
  gem 'bcrypt_pbkdf'
  gem 'ed25519'
  gem 'net-scp'
  gem 'net-ssh'
end
